### ISSUE TITLE
csclub.html has syntax errors

### ISSUE THREAD

**Issue by ViciousCupcake** [ebeohp/teaching-git#1]
[csclub.html](https://github.com/ebeohp/teaching-git/blob/master/csclub.html) has syntax errors

probably should add a `<!DOCTYPE>` declaration and wrap your text into a `<body>` tag to be safe.

I can work on fixing this fundamental problem once hacktoberfest starts ;)

**Comment by ViciousCupcake** [comment]
while we're at it lets add a readme

**Comment by ebeohp** [comment]
Haha, I did that because my computer was lagging and I didnt want to waste time writing actual code during the lesson
